packageVersion: 00
releaseCandidateVersion: 00
workingDir: charts
url: https://kiali.org/helm-charts/kiali-server-1.24.0.tgz
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
