apiVersion: v1
version: 0.1.2
appVersion: 0.1.0
annotations:
  catalog.rancher.io/certified: rancher
  catalog.rancher.io/namespace: cattle-monitoring-system
  catalog.rancher.io/release-name: rancher-pushprox
  catalog.cattle.io/hidden: "true"
description: Sets up a deployment of the PushProx proxy and a DaemonSet of PushProx clients.
name: rancher-pushprox
type: application